'use strict';
const state={items:[],selected:0,voicebanks:[],models:[],renderers:[],busy:false,analysisTimer:0,analysisController:null,playerURL:''};
const $=id=>document.getElementById(id),current=()=>state.items[state.selected];
function newItem(){return{text:'',reading:'',morae:[],voicebank_id:'',model_id:'none',renderer:'',tone:'C4',mora_duration_ms:120,pause_duration_ms:180,intonation_strength:0,apply_pitch:false,points:[]}}
function renderList(){const root=$('utterances');root.replaceChildren();state.items.forEach((item,index)=>{const element=document.createElement('div');element.className='utterance '+(index===state.selected?'active':'');element.textContent=item.text||'（空の発話）';const small=document.createElement('small');small.textContent=item.reading||'読み未解析';element.appendChild(small);element.onclick=()=>selectItem(index);root.appendChild(element)})}
function saveControls(){const item=current();if(!item)return;Object.assign(item,{text:$('text').value,voicebank_id:$('voicebank').value,model_id:$('model').value,renderer:$('renderer').value,tone:$('tone').value,mora_duration_ms:Number($('mora').value)||120,pause_duration_ms:Number($('pause').value)||180,intonation_strength:Number($('intonation').value),apply_pitch:$('applyPitch').checked})}
function loadControls(){const item=current();if(!item)return;$('text').value=item.text;$('voicebank').value=item.voicebank_id;$('model').value=item.model_id;$('renderer').value=item.renderer;$('tone').value=item.tone;$('mora').value=item.mora_duration_ms;$('pause').value=item.pause_duration_ms;$('intonation').value=item.intonation_strength||0;$('applyPitch').checked=!!item.apply_pitch;$('intonationValue').textContent=$('intonation').value;$('reading').textContent=item.reading?'読み: '+item.reading:'';pitchEditor.draw()}
function remapPoints(oldMorae,newMorae,oldPoints){const rows=oldMorae.length+1,cols=newMorae.length+1,dp=Array.from({length:rows},()=>Array(cols).fill(0));for(let i=1;i<rows;i++)for(let j=1;j<cols;j++)dp[i][j]=oldMorae[i-1].mora===newMorae[j-1].mora?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]);const result=Array(newMorae.length).fill(0);let i=oldMorae.length,j=newMorae.length;while(i&&j){if(oldMorae[i-1].mora===newMorae[j-1].mora){result[j-1]=oldPoints[i-1]||0;i--;j--}else if(dp[i-1][j]>=dp[i][j-1])i--;else j--}return result}
async function analyze(item,signal){if(!item.text.trim()){item.reading='';item.morae=[];item.points=[];return}const text=item.text,data=await window.utauAPI.post('/api/analyze',{text},{signal});if(signal.aborted||item.text!==text)return;item.points=remapPoints(item.morae||[],data.morae||[],item.points||[]);item.reading=data.reading;item.morae=data.morae}
function scheduleAnalyze(){clearTimeout(state.analysisTimer);state.analysisController?.abort();const item=current();state.analysisTimer=setTimeout(async()=>{const controller=new AbortController();state.analysisController=controller;try{await analyze(item,controller.signal);if(item===current()){loadControls();renderList()}}catch(error){if(error.name!=='AbortError')$('status').textContent='読み解析エラー: '+error.message}},250)}
async function ensureAnalyzed(item){clearTimeout(state.analysisTimer);if(state.analysisController)state.analysisController.abort();const controller=new AbortController();state.analysisController=controller;await analyze(item,controller.signal)}
function selectItem(index){saveControls();state.selected=index;loadControls();renderList()}
function addUtterance(){saveControls();state.items.push(newItem());state.selected=state.items.length-1;renderList();loadControls();$('text').focus()}
function removeUtterance(){if(state.items.length<=1)return;state.items.splice(state.selected,1);state.selected=Math.min(state.selected,state.items.length-1);renderList();loadControls()}
function moveUtterance(delta){saveControls();const from=state.selected,to=from+delta;if(to<0||to>=state.items.length)return;[state.items[from],state.items[to]]=[state.items[to],state.items[from]];state.selected=to;renderList();loadControls()}
function option(value,label){const item=document.createElement('option');item.value=value;item.textContent=label;return item}
async function loadOptions(){if(!window.utauAPI)throw new Error('APIクライアントの読み込みに失敗しました');const[health,vb,rr,mm]=await Promise.all([window.utauAPI.get('/api/health'),window.utauAPI.get('/api/voicebanks'),window.utauAPI.get('/api/renderers'),window.utauAPI.get('/api/models')]);state.voicebanks=vb.voicebanks||[];state.renderers=rr.renderers||[];state.models=mm.models||[];$('voicebank').replaceChildren(...state.voicebanks.map(v=>option(v.id,v.name)));$('model').replaceChildren(option('none','なし'),...state.models.map(v=>option(v.id,v.display_name)));$('renderer').replaceChildren(option('','サーバー既定: '+rr.default_renderer),...state.renderers.map(v=>option(v.id,v.display_name+(v.experimental?'（実験）':''))));if(!state.items.length)state.items=[newItem()];for(const item of state.items)if(!item.voicebank_id)item.voicebank_id=state.voicebanks[0]?.id||'';setConnection('connected',`● 接続済み · ${health.engine}`);loadControls();renderList()}
function changeVoicebank(){saveControls();renderList()}
async function reloadVoicebanks(){try{await window.utauAPI.post('/api/voicebanks/reload',{});await loadOptions();$('status').textContent='音源を再読込しました'}catch(error){$('status').textContent='音源再読込エラー: '+error.message}}
function makeRequest(item){const request={text:item.text,voicebank_id:item.voicebank_id,model_id:item.model_id,renderer:item.renderer,tone:item.tone,mora_duration_ms:item.mora_duration_ms,pause_duration_ms:item.pause_duration_ms,intonation_strength:item.intonation_strength||0,apply_pitch:!!item.apply_pitch};if(item.apply_pitch&&item.points?.some(value=>Math.abs(value)>.1))request.manual_pitch={version:1,reading:item.reading,mode:'offset',points:item.points.map((cents,position)=>({position,cents}))};return request}
function safeName(value){return String(value||'').trim().replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,' ').slice(0,80)||'utterance'}
function outputName(item,index){const bank=state.voicebanks.find(v=>v.id===item.voicebank_id);return`${safeName(bank?.name||'voicebank')}_${safeName(item.text)||`utterance-${index+1}`}.wav`}
function downloadBlob(blob,name){const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function setBusy(value){state.busy=value;document.querySelectorAll('button').forEach(button=>button.disabled=value)}
async function synthesizeSelected(){if(state.busy)return;saveControls();const item=current();if(!item.text.trim())return;setBusy(true);$('status').textContent='合成中...';try{await ensureAnalyzed(item);const blob=await window.utauAPI.audio(makeRequest(item));if(state.playerURL)URL.revokeObjectURL(state.playerURL);state.playerURL=URL.createObjectURL(blob);$('player').src=state.playerURL;$('player').style.display='block';await $('player').play();$('status').textContent='完了'}catch(error){$('status').textContent='合成エラー: '+error.message}finally{setBusy(false)}}
async function saveSelected(){if(state.busy)return;saveControls();const item=current();if(!item.text.trim())return;setBusy(true);$('status').textContent='保存中...';try{await ensureAnalyzed(item);downloadBlob(await window.utauAPI.audio(makeRequest(item)),outputName(item,state.selected));$('status').textContent='保存完了'}catch(error){$('status').textContent='合成エラー: '+error.message}finally{setBusy(false)}}
async function synthesizeAll(){if(state.busy)return;saveControls();setBusy(true);$('status').textContent='全発話を合成中...';try{const items=[];for(const[index,item]of state.items.entries()){if(!item.text.trim())continue;await ensureAnalyzed(item);items.push({name:outputName(item,index),request:makeRequest(item)})}if(items.length)downloadBlob(await window.utauAPI.batch(items),'utautts-audio.zip');$('status').textContent=`${items.length}件を書き出しました`}catch(error){$('status').textContent='合成エラー: '+error.message}finally{setBusy(false)}}
function setConnection(stateValue,label){const element=$('connectionStatus');element.dataset.state=stateValue;element.textContent=label}
window.addEventListener('utautts-api-ok',()=>{if($('connectionStatus').dataset.state==='error')setConnection('connected','● 接続済み')});window.addEventListener('utautts-api-error',event=>setConnection('error','● 接続エラー: '+event.detail.error.message));
const pitchEditor=window.createPitchEditor($('pitch'),()=>current()?.points||[],saveControls);$('text').oninput=()=>{saveControls();renderList();scheduleAnalyze()};window.addEventListener('beforeunload',()=>{if(state.playerURL)URL.revokeObjectURL(state.playerURL)});loadOptions().catch(error=>{$('status').textContent='初期化エラー: '+error.message;setConnection('error','● バックエンドに接続できません')});
