'use strict';
window.createPitchEditor=function(canvas,getPoints,onChange){
  const ctx=canvas.getContext('2d');let dragging=-1;
  const geometry=()=>({width:canvas.width,height:canvas.height,center:canvas.height/2,scale:Math.max(0.18,Math.min(.4,canvas.height/720))});
  function resize(){const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1,width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}draw()}
  function draw(){const{width,height,center,scale}=geometry();ctx.clearRect(0,0,width,height);ctx.lineWidth=1;for(const cents of[-300,0,300]){const y=center-cents*scale;ctx.strokeStyle=cents===0?'#93b99e':'#d7e3da';ctx.setLineDash(cents===0?[]:[4,5]);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke()}ctx.setLineDash([]);const points=getPoints()||[];if(!points.length)return;ctx.lineWidth=2;ctx.strokeStyle=ctx.fillStyle='#58a875';ctx.beginPath();points.forEach((value,index)=>{const x=points.length===1?width/2:index*(width-32)/(points.length-1)+16,y=center-value*scale;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();points.forEach((value,index)=>{const x=points.length===1?width/2:index*(width-32)/(points.length-1)+16,y=center-value*scale;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill()})}
  canvas.onpointerdown=event=>{const points=getPoints()||[];if(!points.length)return;canvas.setPointerCapture(event.pointerId);const x=event.offsetX*(canvas.width/canvas.clientWidth);dragging=points.length===1?0:Math.max(0,Math.min(points.length-1,Math.round((x-16)*(points.length-1)/(canvas.width-32))))};
  canvas.onpointermove=event=>{if(dragging<0)return;const rect=canvas.getBoundingClientRect(),{center,scale}=geometry(),y=(event.clientY-rect.top)*canvas.height/rect.height;getPoints()[dragging]=Math.round(Math.max(-300,Math.min(300,(center-y)/scale)));draw()};
  canvas.onpointerup=()=>{dragging=-1;onChange()};canvas.onpointercancel=canvas.onpointerup;new ResizeObserver(resize).observe(canvas);return{draw,resize};
};
